### 1. Import the numpy package under the name np

In [1]:
import numpy as np 

### Print the numpy version and the configuration

In [3]:
np.version.version

'1.12.1'

In [9]:
np.__config__.show

<function numpy.__config__.show>

### 3. Create a null vector of size 10

In [12]:
np.zeros((10,1),dtype = np.int)

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0]])

In [13]:
np.zeros((10,1))

array([[ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.]])

### How to find the memory size of any array

In [14]:
a=[1,2,3,4,5]
np_array= np.array(a)

In [15]:
np_array

array([1, 2, 3, 4, 5])

In [20]:
np_array.nbytes

20

In [3]:
import numpy as np 
help(np.nbytes)


Help on _typedict in module numpy.core.numerictypes object:

class _typedict(builtins.dict)
 |  Base object for a dictionary for look-up with any alias for an array dtype.
 |  
 |  Instances of `_typedict` can not be used as dictionaries directly,
 |  first they have to be populated.
 |  
 |  Method resolution order:
 |      _typedict
 |      builtins.dict
 |      builtins.object
 |  
 |  Methods defined here:
 |  
 |  __getitem__(self, obj)
 |      x.__getitem__(y) <==> x[y]
 |  
 |  ----------------------------------------------------------------------
 |  Data descriptors defined here:
 |  
 |  __dict__
 |      dictionary for instance variables (if defined)
 |  
 |  __weakref__
 |      list of weak references to the object (if defined)
 |  
 |  ----------------------------------------------------------------------
 |  Methods inherited from builtins.dict:
 |  
 |  __contains__(self, key, /)
 |      True if D has a key k, else False.
 |  
 |  __delitem__(self, key, /)
 |      Delete 

In [21]:
np_array.itemsize

4

###  How to get the documentation of the numpy add function from the command line?

In [24]:
np.info(np.add)

add(x1, x2[, out])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).

Returns
-------
add : ndarray or scalar
    The sum of `x1` and `x2`, element-wise.  Returns a scalar if
    both  `x1` and `x2` are scalars.

Notes
-----
Equivalent to `x1` + `x2` in terms of array broadcasting.

Examples
--------
>>> np.add(1.0, 4.0)
5.0
>>> x1 = np.arange(9.0).reshape((3, 3))
>>> x2 = np.arange(3.0)
>>> np.add(x1, x2)
array([[  0.,   2.,   4.],
       [  3.,   5.,   7.],
       [  6.,   8.,  10.]])


## Create a null vector of size 10 but the fifth value which is 1

In [5]:
 a= np.zeros((10,1))

In [6]:
a[4]= 1

In [7]:
a 

array([[ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 1.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.]])

### Create a vector with values ranging from 10 to 49

In [31]:
import numpy as np 
vector1 =np.arange(10,50)

In [32]:
vector1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

### 8. Reverse a vector (first element becomes last)

In [33]:
array1=np.array([1,2,3,4,5])
array_rev = array1[::-1]

In [34]:
array_rev

array([5, 4, 3, 2, 1])

### 9. Create a 3x3 matrix with values ranging from 0 to 8

In [35]:
array1 = np.arange(0,9)
array1.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### Find indices of non-zero elements from [1,2,0,0,4,0]

In [39]:
nz= np.nonzero([1,2,0,0,4,0])

In [40]:
nz

(array([0, 1, 4], dtype=int64),)

### 11. Create a 3x3 identity matrix

In [43]:
np.identity(3,dtype= int) ## default is float

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [64]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

### 12. Create a 3x3x3 array with random values

In [8]:
np.random.rand(3,3,3)

array([[[ 0.78743472,  0.47988418,  0.78030659],
        [ 0.80637244,  0.98969628,  0.89549429],
        [ 0.51214799,  0.5323447 ,  0.89009815]],

       [[ 0.04374189,  0.48177568,  0.95540157],
        [ 0.84400757,  0.08179355,  0.3585016 ],
        [ 0.29451752,  0.53901445,  0.71911891]],

       [[ 0.38925798,  0.32850001,  0.01842706],
        [ 0.12847736,  0.95233198,  0.62028646],
        [ 0.93157267,  0.94054593,  0.39330705]]])

### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [49]:
array3= np.random.rand(10,10)


In [54]:
max(array3)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [9]:
np.info(max)

max(iterable, *[, default=obj, key=func]) -> value
max(arg1, arg2, *args, *[, key=func]) -> value

With a single iterable argument, return its biggest item. The
default keyword-only argument specifies an object to return if
the provided iterable is empty.
With two or more arguments, return the largest argument.


In [55]:
array3.max()

0.97889380179069763

In [56]:
array3.min()

0.0087199230362204894

### 14. Create a random vector of size 30 and find the mean value 

In [62]:
array4 = np.random.rand(30)
array4

array([ 0.93770245,  0.71879995,  0.05465597,  0.7980707 ,  0.6267056 ,
        0.75186364,  0.64061284,  0.31780984,  0.37924354,  0.73807364,
        0.79448083,  0.36919839,  0.20055831,  0.42576767,  0.8981196 ,
        0.92780656,  0.97398668,  0.04568382,  0.31270835,  0.83207473,
        0.09079658,  0.78634889,  0.25529891,  0.298776  ,  0.97879288,
        0.42656593,  0.93761536,  0.02152669,  0.86388744,  0.95300342])

In [63]:
array4.mean()

0.57855117417970148

In [65]:
np.random.rand(30).mean()

0.54824950757462199

### 15. Create a 2d array with 1 on the border and 0 inside

In [90]:
array5 = np.ones((3,3),dtype = int)

In [91]:
array5

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [93]:
array5[1,1]=0

In [94]:
array5

array([[1, 1, 1],
       [1, 0, 1],
       [1, 1, 1]])

In [121]:
array6 = np.ones((4,4),dtype = int)

In [122]:
array6

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [123]:
array6[1:-1,1:-1]=0

In [10]:
ar = np.arange(3,15).reshape((3,4))

In [11]:
ar 

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10],
       [11, 12, 13, 14]])

In [12]:
ar[1:-1,1:-1]=0

In [16]:
ar 

array([[ 1,  1,  1,  6],
       [ 1,  1,  1, 10],
       [11, 12, 13, 14]])

In [ ]:
ar[0:-1,0:-1]=1

In [15]:
ar 

array([[ 1,  1,  1,  6],
       [ 1,  1,  1, 10],
       [11, 12, 13, 14]])

### 16. How to add a border (filled with 0's) around an existing array?

In [17]:
np.info(np.pad)

 pad(array, pad_width, mode, **kwargs)

Pads an array.

Parameters
----------
array : array_like of rank N
    Input array
pad_width : {sequence, array_like, int}
    Number of values padded to the edges of each axis.
    ((before_1, after_1), ... (before_N, after_N)) unique pad widths
    for each axis.
    ((before, after),) yields same before and after pad for each axis.
    (pad,) or int is a shortcut for before = after = pad width for all
    axes.
mode : str or function
    One of the following string values or a user supplied function.

    'constant'
        Pads with a constant value.
    'edge'
        Pads with the edge values of array.
    'linear_ramp'
        Pads with the linear ramp between end_value and the
        array edge value.
    'maximum'
        Pads with the maximum value of all or part of the
        vector along each axis.
    'mean'
        Pads with the mean value of all or part of the
        vector along each axis.
    'median'
        Pads with the med

In [18]:
ar = np.arange(1,13).reshape(3,4)

In [19]:
ar

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [20]:
np.info(np.pad)

 pad(array, pad_width, mode, **kwargs)

Pads an array.

Parameters
----------
array : array_like of rank N
    Input array
pad_width : {sequence, array_like, int}
    Number of values padded to the edges of each axis.
    ((before_1, after_1), ... (before_N, after_N)) unique pad widths
    for each axis.
    ((before, after),) yields same before and after pad for each axis.
    (pad,) or int is a shortcut for before = after = pad width for all
    axes.
mode : str or function
    One of the following string values or a user supplied function.

    'constant'
        Pads with a constant value.
    'edge'
        Pads with the edge values of array.
    'linear_ramp'
        Pads with the linear ramp between end_value and the
        array edge value.
    'maximum'
        Pads with the maximum value of all or part of the
        vector along each axis.
    'mean'
        Pads with the mean value of all or part of the
        vector along each axis.
    'median'
        Pads with the med

In [22]:
np.pad(ar,1,mode='constant',constant_values=10)

array([[10, 10, 10, 10, 10, 10],
       [10,  1,  2,  3,  4, 10],
       [10,  5,  6,  7,  8, 10],
       [10,  9, 10, 11, 12, 10],
       [10, 10, 10, 10, 10, 10]])

In [23]:
np.pad(ar,2,mode='edge')

array([[ 1,  1,  1,  2,  3,  4,  4,  4],
       [ 1,  1,  1,  2,  3,  4,  4,  4],
       [ 1,  1,  1,  2,  3,  4,  4,  4],
       [ 5,  5,  5,  6,  7,  8,  8,  8],
       [ 9,  9,  9, 10, 11, 12, 12, 12],
       [ 9,  9,  9, 10, 11, 12, 12, 12],
       [ 9,  9,  9, 10, 11, 12, 12, 12]])

## what is the result of following problem 

In [24]:
0*np.nan

nan

In [25]:
np.nan == np.nan

False

In [26]:
np.nan is np.nan

True

In [27]:
np.inf>np.nan

False

In [28]:
np.nan - np.nan

nan

In [29]:
0.3==3*0.1

False

In [33]:
int is float 

False

## Creat 5* 5 matrix with the values 1,2,3,4 just below the diagonal 

### 20. consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element 

In [34]:
6*7*8

336

In [36]:
ar3 = np.arange(3,339).reshape(6,7,8)

In [37]:
ar3 

array([[[  3,   4,   5,   6,   7,   8,   9,  10],
        [ 11,  12,  13,  14,  15,  16,  17,  18],
        [ 19,  20,  21,  22,  23,  24,  25,  26],
        [ 27,  28,  29,  30,  31,  32,  33,  34],
        [ 35,  36,  37,  38,  39,  40,  41,  42],
        [ 43,  44,  45,  46,  47,  48,  49,  50],
        [ 51,  52,  53,  54,  55,  56,  57,  58]],

       [[ 59,  60,  61,  62,  63,  64,  65,  66],
        [ 67,  68,  69,  70,  71,  72,  73,  74],
        [ 75,  76,  77,  78,  79,  80,  81,  82],
        [ 83,  84,  85,  86,  87,  88,  89,  90],
        [ 91,  92,  93,  94,  95,  96,  97,  98],
        [ 99, 100, 101, 102, 103, 104, 105, 106],
        [107, 108, 109, 110, 111, 112, 113, 114]],

       [[115, 116, 117, 118, 119, 120, 121, 122],
        [123, 124, 125, 126, 127, 128, 129, 130],
        [131, 132, 133, 134, 135, 136, 137, 138],
        [139, 140, 141, 142, 143, 144, 145, 146],
        [147, 148, 149, 150, 151, 152, 153, 154],
        [155, 156, 157, 158, 159, 160, 161, 16

In [39]:
ar3.flatten()[100]

103

In [40]:
np.unravel_index(100,(6,7,8))

(1, 5, 4)

## Multiply 5 * 3 and 3 * 2 matrix 

In [41]:
ar1 = np.random.rand(5,3)
ar2= np.random.rand(3,2)

In [42]:
ar1 

array([[ 0.23830554,  0.12532109,  0.56817993],
       [ 0.66922032,  0.98937968,  0.8483657 ],
       [ 0.24499293,  0.92043259,  0.82129892],
       [ 0.8953348 ,  0.85552888,  0.56283623],
       [ 0.97685398,  0.77492275,  0.88845608]])

In [43]:
ar2 

array([[ 0.66676033,  0.87803616],
       [ 0.80749855,  0.11087636],
       [ 0.32164852,  0.83862622]])

In [45]:
np.dot(ar1,ar2)

array([[ 0.44284352,  0.69962662],
       [ 1.5180078 ,  1.40876018],
       [ 1.17076914,  1.00592968],
       [ 1.4688475 ,  1.35300349],
       [ 1.56284707,  1.68871629]])

In [46]:
ar1 @ ar2 

array([[ 0.44284352,  0.69962662],
       [ 1.5180078 ,  1.40876018],
       [ 1.17076914,  1.00592968],
       [ 1.4688475 ,  1.35300349],
       [ 1.56284707,  1.68871629]])

### 21. Create a checkerboard 8x8 matrix using the tile function

In [48]:
np.info(np.tile)

 tile(A, reps)

Construct an array by repeating A the number of times given by reps.

If `reps` has length ``d``, the result will have dimension of
``max(d, A.ndim)``.

If ``A.ndim < d``, `A` is promoted to be d-dimensional by prepending new
axes. So a shape (3,) array is promoted to (1, 3) for 2-D replication,
or shape (1, 1, 3) for 3-D replication. If this is not the desired
behavior, promote `A` to d-dimensions manually before calling this
function.

If ``A.ndim > d``, `reps` is promoted to `A`.ndim by pre-pending 1's to it.
Thus for an `A` of shape (2, 3, 4, 5), a `reps` of (2, 2) is treated as
(1, 1, 2, 2).

Note : Although tile may be used for broadcasting, it is strongly
recommended to use numpy's broadcasting operations and functions.

Parameters
----------
A : array_like
    The input array.
reps : array_like
    The number of repetitions of `A` along each axis.

Returns
-------
c : ndarray
    The tiled output array.

See Also
--------
repeat : Repeat elements of an array.
br

In [49]:
arra1 = np.array([0,1,2])

In [50]:
np.tile(arra1,(8,8))

array([[0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0,
        1, 2],
       [0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0,
        1, 2],
       [0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0,
        1, 2],
       [0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0,
        1, 2],
       [0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0,
        1, 2],
       [0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0,
        1, 2],
       [0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0,
        1, 2],
       [0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0,
        1, 2]])

### 22. Normalize a 5x5 random matrix  

In [53]:
arra2 = np.random.rand(5,5)

In [54]:
arra2 

array([[  2.37428342e-01,   3.48351010e-01,   1.36764274e-01,
          5.05504330e-01,   3.91173285e-01],
       [  7.52647661e-01,   9.25181422e-04,   9.10348088e-01,
          9.41150580e-01,   8.17825290e-01],
       [  9.23043681e-01,   4.90534061e-01,   8.83945945e-01,
          5.95536618e-02,   1.66721836e-01],
       [  2.86574056e-01,   8.77360912e-01,   1.72296908e-01,
          5.52625413e-01,   6.74743558e-01],
       [  8.59003362e-01,   9.17728577e-01,   1.54287148e-01,
          7.41197784e-01,   3.53964071e-01]])

In [56]:
maxm = arra2.max()
minm = arra2.min()

In [57]:
maxm 

0.941150579967867

In [59]:
minm

0.00092518142210762377

In [60]:
normarra2 = (arra2 - minm)/(maxm-minm)

In [61]:
normarra2 

array([[ 0.25153879,  0.36951334,  0.14447503,  0.53665765,  0.41505803],
       [ 0.79951305,  0.        ,  0.96723925,  1.        ,  0.86883434],
       [ 0.98074196,  0.52073564,  0.93915859,  0.06235577,  0.17633714],
       [ 0.30380893,  0.93215492,  0.18226664,  0.58677444,  0.71665622],
       [ 0.91263029,  0.97508895,  0.16311192,  0.78733525,  0.37548325]])

### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA)

In [67]:
np.dtype('red')

TypeError: data type "red" not understood

In [68]:
np.info(np.dtype)

 dtype()

dtype(obj, align=False, copy=False)

Create a data type object.

A numpy array is homogeneous, and contains elements described by a
dtype object. A dtype object can be constructed from different
combinations of fundamental numeric types.

Parameters
----------
obj
    Object to be converted to a data type object.
align : bool, optional
    Add padding to the fields to match what a C compiler would output
    for a similar C-struct. Can be ``True`` only if `obj` is a dictionary
    or a comma-separated string. If a struct dtype is being created,
    this also sets a sticky alignment flag ``isalignedstruct``.
copy : bool, optional
    Make a new copy of the data-type object. If ``False``, the result
    may just be a reference to a built-in data-type object.

See also
--------
result_type

Examples
--------
Using array-scalar type:

>>> np.dtype(np.int16)
dtype('int16')

Structured type, one field name 'f1', containing int16:

>>> np.dtype([('f1', np.int16)])
dtype([('f1', '<i2

In [69]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])

TypeError: data type "r" not understood

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place

In [95]:
ara3 = np.arange(1,15)

In [96]:
ara3[(ara3>=3)  & (ara3<8)] = ara3[(ara3>=3)  & (ara3<8)] *-1

In [97]:
ara3

array([ 1,  2, -3, -4, -5, -6, -7,  8,  9, 10, 11, 12, 13, 14])