# Data Science Intro 
---
### What is data science ? 
--- 
- Analysis/Visualisation/Machine Learning ? 
## References for requirement 
- Openstax 


In [1]:
[1,2,3,4]

[1, 2, 3, 4]

In [2]:
import array 

In [3]:
array.array('i',[1,2,3,4])

array('i', [1, 2, 3, 4])

In [5]:
[1,'a']

[1, 'a']

In [6]:
array.array('i',[1,'a'])

TypeError: an integer is required (got type str)

### Numpy Array 

In [7]:
import numpy as np 

In [19]:
np.array([1,2,3,4]).dtype


dtype('int32')

In [18]:
np.array([1,2,'s',6.0]).dtype 

dtype('<U11')

In [10]:
lst=[1,2,3,4]

In [12]:
import os 
os.path.join 


<function ntpath.join>

In [13]:
os.path.join('hello','world')

'hello\\world'

In [15]:
from os import path
path.join('one','two')

'one\\two'

In [20]:
np.array([[1,4,5,6,7],[3,4,6,9,1]])

array([[1, 4, 5, 6, 7],
       [3, 4, 6, 9, 1]])

In [21]:
np.arange(0,18)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [22]:
np.arange(0,18).reshape((2,3,3))

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [23]:
%timeit [x**2 for x in range(0,999)]

1000 loops, best of 3: 929 µs per loop


## Body mass index using numpy 

In [1]:
height = [1.73,1.68,1.71,1.89,1.79]
weight = [65.4,66.8,73,75.2,66.7]

In [2]:
height 

[1.73, 1.68, 1.71, 1.89, 1.79]

In [3]:
weight 

[65.4, 66.8, 73, 75.2, 66.7]

In [4]:
weight/height**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [5]:
import numpy as np 

In [6]:
np_height = np.array(height)

In [7]:
np_height 

array([ 1.73,  1.68,  1.71,  1.89,  1.79])

In [8]:
np_weight = np.array(weight)

In [9]:
np_weight 

array([ 65.4,  66.8,  73. ,  75.2,  66.7])

In [10]:
bmi = np_weight/np_height**2 

In [11]:
bmi 

array([ 21.85171573,  23.66780045,  24.96494648,  21.05204222,  20.81707812])

## Numpy subsetting 

In [12]:
bmi[1]

23.66780045351474

In [13]:
bmi>23

array([False,  True,  True, False, False], dtype=bool)

In [14]:
bmi[bmi>23]

array([ 23.66780045,  24.96494648])

### Type of numpy arrays 

In [15]:
type(np_height)   ## nd.array - n dimensional array

numpy.ndarray

In [16]:
type(np_weight)

numpy.ndarray

## Create 2D numpy array 

In [18]:
np_2d = np.array([[1,2,3,4],[5,6,7,8]])

In [19]:
np_2d 

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [20]:
np_2d.shape

(2, 4)

## Sub setting 2D array 

In [24]:
np_2d[1,3] ## the value before comma represents row and after represents column

8

In [2]:
lst= [1,2,3,4]

In [4]:
import numpy as np
np_lst= np.array(lst)


In [5]:
np_lst

array([1, 2, 3, 4])

In [6]:
lst*2 

[1, 2, 3, 4, 1, 2, 3, 4]

In [7]:
np_lst*2

array([2, 4, 6, 8])

In [8]:
arra2= np.arange(1,25)

In [9]:
arra2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [18]:
arra3= arra2.reshape(4,6)

In [11]:
arra2[1:3]

array([2, 3])

In [19]:
arra3

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [12]:
arra2[1:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24])

In [13]:
arra2[2:]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22, 23, 24])

In [14]:
arra2[1:3][1:3]

array([3])

In [16]:
arra2[1:3, 1:3]

IndexError: too many indices for array

In [22]:
arra3

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [21]:
arra3[1:3,1:3]

array([[ 8,  9],
       [14, 15]])

In [23]:
arra3.shape

(4, 6)

In [24]:
arra3.size

24

In [25]:
arra3.ndim

2

In [29]:
r1 = np.random.random(50)

In [30]:
r1

array([ 0.60896242,  0.08356595,  0.38348067,  0.42503943,  0.68664746,
        0.48594709,  0.24086638,  0.98536458,  0.53440207,  0.80205796,
        0.46656647,  0.75609011,  0.7537241 ,  0.39122449,  0.27550931,
        0.50709399,  0.55149429,  0.58733845,  0.37981554,  0.79074814,
        0.06381197,  0.39592618,  0.24566539,  0.23056466,  0.79651046,
        0.01721432,  0.12863634,  0.59317624,  0.81521867,  0.19329991,
        0.06263815,  0.96610219,  0.02592898,  0.68827302,  0.4417146 ,
        0.0206027 ,  0.0648882 ,  0.2852228 ,  0.01456729,  0.35699561,
        0.81165049,  0.51799322,  0.00995707,  0.50419379,  0.24938058,
        0.77331927,  0.24027241,  0.1401145 ,  0.60813136,  0.99046193])

In [33]:
r2= r1.reshape(10,5)

In [34]:
r2

array([[ 0.60896242,  0.08356595,  0.38348067,  0.42503943,  0.68664746],
       [ 0.48594709,  0.24086638,  0.98536458,  0.53440207,  0.80205796],
       [ 0.46656647,  0.75609011,  0.7537241 ,  0.39122449,  0.27550931],
       [ 0.50709399,  0.55149429,  0.58733845,  0.37981554,  0.79074814],
       [ 0.06381197,  0.39592618,  0.24566539,  0.23056466,  0.79651046],
       [ 0.01721432,  0.12863634,  0.59317624,  0.81521867,  0.19329991],
       [ 0.06263815,  0.96610219,  0.02592898,  0.68827302,  0.4417146 ],
       [ 0.0206027 ,  0.0648882 ,  0.2852228 ,  0.01456729,  0.35699561],
       [ 0.81165049,  0.51799322,  0.00995707,  0.50419379,  0.24938058],
       [ 0.77331927,  0.24027241,  0.1401145 ,  0.60813136,  0.99046193]])

In [2]:
import numpy as np 
r3 = np.random.randint(10,30,size= 25)

In [3]:
r3 

array([12, 14, 20, 25, 23, 24, 11, 29, 23, 28, 19, 28, 12, 16, 26, 26, 19,
       29, 20, 18, 10, 28, 11, 16, 11])

In [4]:
r3.mean()

19.920000000000002

In [5]:
np.median(r3)

20.0

In [6]:
r3.std()

6.4182240534278634

In [7]:
np.var(r3)

41.193599999999996

In [8]:
r3

array([12, 14, 20, 25, 23, 24, 11, 29, 23, 28, 19, 28, 12, 16, 26, 26, 19,
       29, 20, 18, 10, 28, 11, 16, 11])

In [9]:
r4= r3.mean()- r3 

In [10]:
r4

array([ 7.92,  5.92, -0.08, -5.08, -3.08, -4.08,  8.92, -9.08, -3.08,
       -8.08,  0.92, -8.08,  7.92,  3.92, -6.08, -6.08,  0.92, -9.08,
       -0.08,  1.92,  9.92, -8.08,  8.92,  3.92,  8.92])

In [11]:
np.split(r3,2)

ValueError: array split does not result in an equal division

In [13]:
r4 = np.append(r4,17)

In [15]:
np.split(r4,2)

[array([ 7.92,  5.92, -0.08, -5.08, -3.08, -4.08,  8.92, -9.08, -3.08,
        -8.08,  0.92, -8.08,  7.92]),
 array([  3.92,  -6.08,  -6.08,   0.92,  -9.08,  -0.08,   1.92,   9.92,
         -8.08,   8.92,   3.92,   8.92,  17.  ])]

In [16]:
r41,r42= np.split(r4,2)

In [17]:
r41

array([ 7.92,  5.92, -0.08, -5.08, -3.08, -4.08,  8.92, -9.08, -3.08,
       -8.08,  0.92, -8.08,  7.92])

In [18]:
r42

array([  3.92,  -6.08,  -6.08,   0.92,  -9.08,  -0.08,   1.92,   9.92,
        -8.08,   8.92,   3.92,   8.92,  17.  ])

In [20]:
np.concatenate((r41,r42))

array([  7.92,   5.92,  -0.08,  -5.08,  -3.08,  -4.08,   8.92,  -9.08,
        -3.08,  -8.08,   0.92,  -8.08,   7.92,   3.92,  -6.08,  -6.08,
         0.92,  -9.08,  -0.08,   1.92,   9.92,  -8.08,   8.92,   3.92,
         8.92,  17.  ])

In [22]:
np.hsplit(r4,2)

[array([ 7.92,  5.92, -0.08, -5.08, -3.08, -4.08,  8.92, -9.08, -3.08,
        -8.08,  0.92, -8.08,  7.92]),
 array([  3.92,  -6.08,  -6.08,   0.92,  -9.08,  -0.08,   1.92,   9.92,
         -8.08,   8.92,   3.92,   8.92,  17.  ])]

In [9]:
import numpy as np 
array1 = np.arange(0,8)

In [11]:
array1.reshape(2,4,1)

array([[[0],
        [1],
        [2],
        [3]],

       [[4],
        [5],
        [6],
        [7]]])

In [12]:
plot(array1)

NameError: name 'plot' is not defined

In [17]:
help

Type help() for interactive help, or help(object) for help about object.

In [3]:
import numpy as np 
help(np.reshape)

Help on function reshape in module numpy.core.fromnumeric:

reshape(a, newshape, order='C')
    Gives a new shape to an array without changing its data.
    
    Parameters
    ----------
    a : array_like
        Array to be reshaped.
    newshape : int or tuple of ints
        The new shape should be compatible with the original shape. If
        an integer, then the result will be a 1-D array of that length.
        One shape dimension can be -1. In this case, the value is
        inferred from the length of the array and remaining dimensions.
    order : {'C', 'F', 'A'}, optional
        Read the elements of `a` using this index order, and place the
        elements into the reshaped array using this index order.  'C'
        means to read / write the elements using C-like index order,
        with the last axis index changing fastest, back to the first
        axis index changing slowest. 'F' means to read / write the
        elements using Fortran-like index order, with the firs